### ISSUE TITLE
Python stopped working

### ISSUE THREAD

**Issue by cl1551** [ver228/tierpsy-tracker#64]
Hello, when I used the Set Parameters function and dragged a avi file into the video file column it said that "Python has stopped working." Can you help me with that? Thanks.

**Comment by cl1551** [comment]
The Anaconda Prompt said "not enough value to unpack <expected 3, got 2>"

**Comment by ver228** [comment]
It is possible is caused by the new version of OpenCV. It seems that they changed the API of some functions and it is breaking the current version of Tierpsy. In order to check if this is the case open an anaconda prompt and type:

```
python -c "import cv2; print(cv2.__version__)"
```
If the value is 4.X.X or similar then it is a problem with the opencv version.

You can try to downgrade it back to 3. If you installed using conda type:
```
conda install opencv=3
```
If you used pip then:
```
pip install opencv-python-headless==3.4.5.20
```

Please let me know if it works. If it is not a problem of the opencv version then I would need more information.

**Comment by cl1551** [comment]
Hello,

When I install the opencv3 it announced me another error.

from .utilsextension import <
ImportError: DLL load failed: The specified module could not be found.

Avelino Javer <notifications@github.com> 于2019年9月6日周五 上午2:54写道：

**Comment by ver228** [comment]
It seems your anaconda installation got broken somehow. It is very hard to say anything with only that information. Try to install opencv using `pip` (maybe first uninstall opencv `conda uninstall opencv` . Otherwise, you might one to either use a new environment or reinstall anaconda completely.

**Comment by cl1551** [comment]
I fixed the opencv issue. Now is 3.4.2. But it still announce me not enough
values to unpack. What extra info do you need? Thanks.

Avelino Javer <notifications@github.com> 于2019年9月10日周二 下午3:36写道：

**Comment by cl1551** [comment]
I change the opencv edition to 3.4.3.18 and the error was fixed. Thank you
for your help!! I really appreciate that!

Chang Li <cl1551@truman.edu> 于2019年9月10日周二 下午4:10写道：
